name: Test ECR Login

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get ECR Credentials
        uses: quantcdn/quant-cloud-ecr-action@v1
        id: ecr-login
        with:
          api_key: ${{ secrets.QUANT_API_KEY }}
          organization: quant
          base_url: https://portal.stage.quantcdn.io/api/v3  # Optional

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.ecr-login.outputs.endpoint }}
          username: ${{ steps.ecr-login.outputs.username }}
          password: ${{ steps.ecr-login.outputs.password }}

      - name: Verify Login
        run: docker info