name: Test ECR Login

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Debug Action Files
        run: |
          ls -la
          ls -la dist/
          cat action.yml

      - name: Update Environment State
        uses: ./
        id: update-environment-state
        with:
          api_key: ${{ secrets.QUANT_API_KEY }}
          organization: 'quant'
          application: 'clap'
          environment: 'production'
          base_url: 'https://portal.stage.quantcdn.io/api/v3'
          action: 'redeploy'
